### ISSUE TITLE
How can i debug when its not working?

### ISSUE THREAD

**Issue by albertusQuelle** [JBassett/plex_webhooks#3]
Hi
i have that configuration.yaml

```
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

plex_webhooks:
  webhook_id: plex_webhook
```

automations.yaml
```
- id: '1607872979615'
  alias: Plex stopped
  description: ''
  trigger:
  - platform: event
    event_type: PLEX_EVENT
    event_data:
      status: STOPPED
  condition: []
  action:
  - scene: scene.lampe_wohnzimmer
  - type: turn_on
    device_id: 98be2dba680b779031d8fce0c4989703
    entity_id: light.fernsehtisch
    domain: light
    brightness_pct: 15
  mode: single
```

added the webhook url of the HASS raspi
![image](https://user-images.githubusercontent.com/2970225/102019588-b6f5e100-3d74-11eb-87da-4910d0e8029e.png)

It does not work unfortunately :/
